<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>8</LangVersion>
        <RootNamespace>Corvette.Chat.Data</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Curiosity.DAL" Version="1.1.1" />
      <PackageReference Include="Curiosity.DAL.EF" Version="1.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.14">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.11" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations" />
    </ItemGroup>

</Project>
